#' @title Acoustic template detection from time-frequency cross-correlations
#'
#' @description \code{template_detector} find sound event occurrences in cross-correlation vectors from \code{\link{template_correlator}}
#' @param template.correlations object of class 'template_correlations' generated by \code{\link{template_correlator}} containing the correlation score vectors.
#' @param cores Numeric. Controls whether parallel computing is applied.
#' It specifies the number of cores to be used. Default is 1 (i.e. no parallel computing).
#' @param threshold Numeric vector of length 1 with a value between 0 and 1 specifying the correlation threshold for detecting sound event occurrences (i.e. correlation peaks). Must be supplied. Correlation scores are forced to between 0 and 1 (by converting negative scores to 0). 0 and 1 represent the lowest and highest similarity to the template respectively.
#' @param pb Logical argument to control progress bar. Default is \code{TRUE}.
#' @param verbose Logical argument to control if some summary messages are printed to the console.
#' @param save.txt Logical argument to control if a '.txt' file in selection table format (compatible with the Raven Pro acoustic analysis software) is saved (using \code{\link[Rraven]{exp_raven}} internally). If so a single file will be saved for each sound file in the directory given by 'path'. For sound files with no detections the file will still be saved but without any data. The name of the selection will contain the name of the sound file. This is useful for long processes in which users might want to stop and resume or when adding new sound files.
#' @param path Character string containing the directory path where the '.txt' files will be saved (only if \code{save.txt = TRUE}). Default is \code{"."} (current working directory).
#' @return The function returns a 'selection_table' (warbleR package's formats, see \code{\link[warbleR]{selection_table}}) or data frame (if sound files can't be found) with the start and end and correlation score for the
#' detected sound events. Template/sound file combinations with no detections are not included in the output (a data frame with 0 rows is returned if nothing is detected).
#' @export
#' @name template_detector
#' @details This function infers sound events occurrences from cross-correlation scores along sound files. Correlation scores must be generated first using \code{\link{template_correlator}}. The output is a data frame (or selection table if sound files are still found in the original path supplied to \code{\link{template_correlator}}, using the warbleR package's format, see \code{\link[warbleR]{selection_table}}) containing the start and end of the detected sound events as well as the cross-correlation score ('scores' column) for each detection. \strong{Note that the detected sounds are assumed to have the same duration as the template, so their start and end correspond to the correlation peak position +/- half the template duration}.
#' @examples
#' {
#'   # load example data
#'   data("lbh1", "lbh2", "lbh_reference")
#'
#'   # save sound files
#'   tuneR::writeWave(lbh1, file.path(tempdir(), "lbh1.wav"))
#'   tuneR::writeWave(lbh2, file.path(tempdir(), "lbh2.wav"))
#'
#'   # template for the first sound file in 'lbh_reference'
#'   templ1 <- lbh_reference[1, ]
#'
#'   # generate template correlations
#'   tc <- template_correlator(templates = templ1, path = tempdir(), files = "lbh1.wav")
#'
#'   # template detection
#'   td <- template_detector(template.correlations = tc, threshold = 0.4)
#'
#'   # diagnose detection
#'   diagnose_detection(
#'     reference =
#'       lbh_reference[lbh_reference$sound.files == "lbh1.wav", ],
#'     detection = td
#'   )
#'
#'   # template for the second and third sound file in 'lbh_reference'
#'   # which have similar song types
#'   templ2 <- lbh_reference[4, ]
#'
#'   # generate template correlations
#'   tc <- template_correlator(
#'     templates = templ2, path = tempdir(),
#'     files = c("lbh1.wav", "lbh2.wav")
#'   )
#'
#'   # template detection
#'   td <- template_detector(template.correlations = tc, threshold = 0.3)
#'
#'   # diagnose detection
#'   diagnose_detection(reference = lbh_reference, detection = td)
#' }
#' @seealso \code{\link{energy_detector}}, \code{\link{template_correlator}}, \code{\link{optimize_template_detector}}
#' @author Marcelo Araya-Salas \email{marcelo.araya@@ucr.ac.cr})
#'
#' @references 
#'  Araya-Salas, M., Smith-Vidaurre, G., Chaverri, G., Brenes, J. C., Chirino, F., Elizondo-Calvo, J., & Rico-Guevara, A. (2023). ohun: An R package for diagnosing and optimizing automatic sound event detection. Methods in Ecology and Evolution, 14, 2259–2271. https://doi.org/10.1111/2041-210X.14170
#' 

template_detector <-
  function(template.correlations,
           cores = 1,
           threshold,
           pb = TRUE,
           verbose = TRUE,
           save.txt = FALSE,
           path = ".") {
    # save start time
    start_time <- proc.time()

    # check arguments
    arguments <- as.list(base::match.call(expand.dots = FALSE))

    # do not check ... arguments
    arguments <- arguments[grep("...", names(arguments), fixed = TRUE, invert = TRUE)]

    # add objects to argument names
    for (i in names(arguments)[-1]) {
      arguments[[i]] <- get(i)
    }

    # check each arguments
    check_results <- check_arguments(fun = arguments[[1]], args = arguments)

    # report errors
    checkmate::reportAssertions(check_results)

    # set clusters for windows OS or more decent OSs
    if (Sys.info()[1] == "Windows" & cores > 1) {
      cl <-
        parallel::makePSOCKcluster(getOption("cl.cores", cores))
    } else {
      cl <- cores
    }

    # loop over scores of each dyad
    sel_table_list <-
      warbleR:::.pblapply(
        pbar = pb,
        X = 1:(length(template.correlations) - 1),
        cl = cl,
        message = "detecting templates",
        total = 1,
        FUN = function(i) {
          
          # get file and template names
          file_template <-
            strsplit(names(template.correlations)[i], "/")[[1]]
          
          # name of the txt file (one per template/sound file combination)
          txt_name <- paste0(file_template[2], "_", file_template[1])

          # if save and file exist then read it
          if (save.txt & file.exists(file.path(path, paste0(txt_name, ".txt")))){
            
            # read file
            suppressWarnings(in_txt <- Rraven::imp_raven(
              path = path,
              files = paste0(txt_name, ".txt"),
              pb = FALSE,
              warbler.format = TRUE, all.data = TRUE
            ))
            
            if (!is.null(in_txt)) {
              sel_table <- in_txt[, c("sound.files", "selec", "start", "end", "template", "scores")]
            } else {
              sel_table <- .empty_detection(file_template[2], type = "template", template = file_template[1]) 
            }
          } else {
          
          # extract data for a dyad
          temp_cor <- template.correlations[[i]]

          ## get peaks as the ones higher than previous and following scores
          peak_position <-
            which(c(FALSE, diff(temp_cor$correlation.scores) > 0) &
              c(rev(diff(
                rev(temp_cor$correlation.scores)
              ) > 0), FALSE) & temp_cor$correlation.scores > threshold)

          # get peaks and their scores
          scores <- temp_cor$correlation.scores[peak_position]

          # get peak position fixing by removing half the duration of the sound event at the start and end of the sound file
          peak_time <-
            seq(
              temp_cor$template.duration / 2,
              temp_cor$file.duration - temp_cor$template.duration / 2,
              length.out = length(temp_cor$correlation.scores)
            )[peak_position]

          # calculate starts as the peak location minus half the template duration
          starts <-
            if (length(peak_time) > 0) {
              peak_time - (temp_cor$template.duration / 2)
            } else {
              NA
            }
          # cannot be negative
          starts[starts < 0] <- 0

          # calculate ends as the peak location plus half the template duration
          ends <-
            if (length(peak_time) > 0) {
              peak_time + (temp_cor$template.duration / 2)
            } else {
              NA
            }

          # cannot be higher than file duration
          ends[ends > temp_cor$file.duration] <- temp_cor$file.duration

          # put results in an extended selection table
          sel_table <-
            data.frame(
              sound.files = file_template[2],
              selec = if (length(scores) > 0) {
                seq_len(length(scores))
              } else {
                1
              },
              start = starts,
              end = ends,
              template = file_template[1],
              scores = if (length(scores) > 0) {
                scores
              } else {
                NA
              }
            )
          
          # save txt file with detections
          if (save.txt){
            if (all(is.na(sel_table$start))){
              .write_empty_raven(X = sel_table, path = path, file.name = txt_name)
            } else {
              Rraven::exp_raven(sel_table, path = path, file.name = txt_name, pb = FALSE, sound.file.path = path)
            }
            
          }
          }

          return(sel_table)
        }
      )

    # put results in a data frame
    detections_df <- do.call(rbind, sel_table_list)

    # remove empty detections (template/sound file combinations with no detections)
    detections_df <- detections_df[!is.na(detections_df$start), ]

    # relabel rows
    rownames(detections_df) <- seq_len(nrow(detections_df))

    # get path from correlation call (stored directly in newer versions)
    corr_call_path <- template.correlations$call_info$path

    if (is.null(corr_call_path)) {
      corr_call_path <-
        try(eval(rlang::call_args(template.correlations$call_info$call)$path), silent = TRUE)
    }

    if (is(corr_call_path, "try-error") |
      is.null(corr_call_path)) {
      corr_call_path <- getwd()
    }

    #  let user know if no detections are found
    if (nrow(detections_df) == 0) {
      if (verbose) {
        message2(color = "silver", x = "no sound events above threshold were detected")
      }
    } else if (all(detections_df$sound.files %in% list.files(path = corr_call_path))) {
      detections_df <-
        warbleR::selection_table(
          X = detections_df,
          path = corr_call_path,
          parallel = cores,
          pb = FALSE,
          verbose = FALSE,
          fix.selec = TRUE
        )

      attributes(detections_df)$call <- base::match.call()

      # add elapsed time
      attributes(detections_df)$elapsed.time.s <-
        as.vector((proc.time() - start_time)[3])
    }
    return(detections_df)
  }
